<?php
/**
 * Created by PhpStorm.
 * User: liuho
 * Date: 2018/4/27
 * Time: 14:54
 */

namespace Ace\plugins\a\ModelManager;

use Illuminate\Database\Capsule\Manager as DB;
use App\BasePlugin;
use Illuminate\Database\Schema\Blueprint;

class ModelManager extends BasePlugin
{
    public function install()
    {
        // 建立一张模型表
        if (!DB::schema()->hasTable('models')) {
            // 如果没有模型表，就安装
            DB::schema()->create('models', function (Blueprint $table) {
                $table->increments('id');
                $table->string('name')->comment('模型名称');
                $table->string('target')->comment('模型唯一标识符');
                $table->string('description')->nullable()->comment('模型描述');
                $table->text('config')->nullable()->comment('模型默认配置');
                $table->timestamps();
            });
        } else {
            echo "\n 模型插件: 数据库中存在模型表，已跳过建表......";
        }

        // 建立一张模块表
        if(!DB::schema()->hasTable('modules')){
            // 没有模块表，创建
            DB::schema()->create('modules',function (Blueprint $table){
               $table->increments('id');
               $table->string('name')->comment('模块名，可中文可英文');
               $table->string('target')->comment('模块对应的表，必须是英文，将在数据库中生成一张对应表');
               $table->text('description')->nullable()->comment('模块描述');
               $table->integer('model_id')->comment('所属模型id');
               $table->integer('module_id')->default(0)->nullable()->comment('上级模块id，默认是0，即顶级模块');
               $table->string('status')->default('使用中')->nullable()->comment('模块状态，使用中，隐藏，删除等');
               $table->text('config')->default('')->nullable()->comment('配置信息，这个模块的对应的表的字段信息');
            });
        }else{
            echo "\n 模型插件: 数据库中存在模块表，已跳过建表......";
        }

        parent::install(); // TODO: Change the autogenerated stub
    }

    // 模型添加
    public function create(){

    }

    // 模型删除
    public function delete(){

    }

    // 模型修改
}